module astra_capu_reconciled_effect_device_a6 #(
  parameter integer TAG_WIDTH   = 8,
  parameter integer ID_WIDTH    = 4,
  parameter integer COUNT_WIDTH = 16
)(
  input  logic                   clk,
  input  logic                   cold_rst_n,
  input  logic                   logic_rst_n,

  input  logic                   device_state_load_valid,
  input  logic [COUNT_WIDTH-1:0] device_state_load_count,

  input  logic                   provision_valid,
  input  logic [TAG_WIDTH-1:0]   provision_tag,
  input  logic [ID_WIDTH-1:0]    provision_incarnation,
  input  logic [ID_WIDTH-1:0]    provision_queue_epoch,
  input  logic [ID_WIDTH-1:0]    provision_slot_id,
  input  logic [ID_WIDTH-1:0]    provision_command_id,
  input  logic [ID_WIDTH-1:0]    provision_effect_id,
  input  logic [ID_WIDTH-1:0]    provision_next_attempt,

  input  logic                   authority_load_valid,
  input  logic                   authority_load_committed,
  input  logic [TAG_WIDTH-1:0]   authority_load_tag,
  input  logic [ID_WIDTH-1:0]    authority_load_incarnation,
  input  logic [ID_WIDTH-1:0]    authority_load_queue_epoch,
  input  logic [ID_WIDTH-1:0]    authority_load_slot_id,
  input  logic [ID_WIDTH-1:0]    authority_load_command_id,
  input  logic [ID_WIDTH-1:0]    authority_load_attempt_id,
  input  logic [ID_WIDTH-1:0]    authority_load_effect_id,

  input  logic                   authority_revoke_valid,
  input  logic [TAG_WIDTH-1:0]   authority_revoke_tag,
  input  logic [ID_WIDTH-1:0]    authority_revoke_incarnation,
  input  logic [ID_WIDTH-1:0]    authority_revoke_queue_epoch,
  input  logic [ID_WIDTH-1:0]    authority_revoke_slot_id,
  input  logic [ID_WIDTH-1:0]    authority_revoke_command_id,
  input  logic [ID_WIDTH-1:0]    authority_revoke_attempt_id,
  input  logic [ID_WIDTH-1:0]    authority_revoke_effect_id,

  input  logic                   command_valid,
  input  logic                   command_commit,
  input  logic [TAG_WIDTH-1:0]   command_authority_tag,
  input  logic [ID_WIDTH-1:0]    command_incarnation,
  input  logic [ID_WIDTH-1:0]    command_queue_epoch,
  input  logic [ID_WIDTH-1:0]    command_slot_id,
  input  logic [ID_WIDTH-1:0]    command_id,
  input  logic [ID_WIDTH-1:0]    command_attempt_id,
  input  logic [ID_WIDTH-1:0]    command_effect_id,

  input  logic                   reconcile_valid,
  input  logic [TAG_WIDTH-1:0]   reconcile_tag,
  input  logic [ID_WIDTH-1:0]    reconcile_incarnation,
  input  logic [ID_WIDTH-1:0]    reconcile_queue_epoch,
  input  logic [ID_WIDTH-1:0]    reconcile_slot_id,
  input  logic [ID_WIDTH-1:0]    reconcile_command_id,
  input  logic [ID_WIDTH-1:0]    reconcile_attempt_id,
  input  logic [ID_WIDTH-1:0]    reconcile_effect_id,
  input  logic [2:0]             reconcile_outcome,

  output logic                   provision_accept,
  output logic                   provision_rejected,
  output logic                   reserve_valid,
  output logic                   reserve_accept,
  output logic                   reserve_rejected,
  output logic                   reconcile_accept,
  output logic                   reconcile_rejected,
  output logic [2:0]             reconcile_reject_code,
  output logic                   frontier_exhausted,

  output logic                   authority_load_accept,
  output logic                   authority_load_rejected,
  output logic                   authority_revoke_accept,
  output logic                   authority_revoke_rejected,
  output logic                   command_forward,
  output logic                   command_rejected,
  output logic [3:0]             command_reject_code,
  output logic                   device_command_accept,
  output logic                   device_completion_valid,
  output logic [COUNT_WIDTH-1:0] effect_count,

  output logic                   persistent_valid,
  output logic [TAG_WIDTH-1:0]   persistent_tag,
  output logic [ID_WIDTH-1:0]    persistent_incarnation,
  output logic [ID_WIDTH-1:0]    persistent_queue_epoch,
  output logic [ID_WIDTH-1:0]    persistent_slot_id,
  output logic [ID_WIDTH-1:0]    persistent_command_id,
  output logic [ID_WIDTH-1:0]    persistent_effect_id,
  output logic [ID_WIDTH-1:0]    persistent_next_attempt,
  output logic                   unresolved_valid,
  output logic [ID_WIDTH-1:0]    unresolved_attempt,
  output logic [2:0]             last_outcome,
  output logic [ID_WIDTH-1:0]    last_resolved_attempt,
  output logic                   terminal_committed,
  output logic                   terminal_conflict,

  output logic                   active_valid,
  output logic                   active_committed,
  output logic                   attempt_spent,
  output logic [TAG_WIDTH-1:0]   active_authority_tag,
  output logic [ID_WIDTH-1:0]    active_incarnation,
  output logic [ID_WIDTH-1:0]    active_queue_epoch,
  output logic [ID_WIDTH-1:0]    active_slot_id,
  output logic [ID_WIDTH-1:0]    active_command_id,
  output logic [ID_WIDTH-1:0]    active_attempt_id,
  output logic [ID_WIDTH-1:0]    active_effect_id
);

  logic [TAG_WIDTH-1:0] reserve_tag;
  logic [ID_WIDTH-1:0]  reserve_incarnation;
  logic [ID_WIDTH-1:0]  reserve_queue_epoch;
  logic [ID_WIDTH-1:0]  reserve_slot_id;
  logic [ID_WIDTH-1:0]  reserve_command_id;
  logic [ID_WIDTH-1:0]  reserve_attempt_id;
  logic [ID_WIDTH-1:0]  reserve_effect_id;

  astra_capu_persistent_outcome_store_a6 #(
    .TAG_WIDTH(TAG_WIDTH),
    .ID_WIDTH(ID_WIDTH)
  ) persistent_store (
    .clk(clk),
    .cold_rst_n(cold_rst_n),
    .provision_valid(provision_valid),
    .provision_tag(provision_tag),
    .provision_incarnation(provision_incarnation),
    .provision_queue_epoch(provision_queue_epoch),
    .provision_slot_id(provision_slot_id),
    .provision_command_id(provision_command_id),
    .provision_effect_id(provision_effect_id),
    .provision_next_attempt(provision_next_attempt),
    .reserve_valid(reserve_valid),
    .reserve_tag(reserve_tag),
    .reserve_incarnation(reserve_incarnation),
    .reserve_queue_epoch(reserve_queue_epoch),
    .reserve_slot_id(reserve_slot_id),
    .reserve_command_id(reserve_command_id),
    .reserve_attempt_id(reserve_attempt_id),
    .reserve_effect_id(reserve_effect_id),
    .reconcile_valid(reconcile_valid),
    .reconcile_tag(reconcile_tag),
    .reconcile_incarnation(reconcile_incarnation),
    .reconcile_queue_epoch(reconcile_queue_epoch),
    .reconcile_slot_id(reconcile_slot_id),
    .reconcile_command_id(reconcile_command_id),
    .reconcile_attempt_id(reconcile_attempt_id),
    .reconcile_effect_id(reconcile_effect_id),
    .reconcile_outcome(reconcile_outcome),
    .provision_accept(provision_accept),
    .provision_rejected(provision_rejected),
    .reserve_accept(reserve_accept),
    .reserve_rejected(reserve_rejected),
    .reconcile_accept(reconcile_accept),
    .reconcile_rejected(reconcile_rejected),
    .reconcile_reject_code(reconcile_reject_code),
    .frontier_exhausted(frontier_exhausted),
    .persistent_valid(persistent_valid),
    .persistent_tag(persistent_tag),
    .persistent_incarnation(persistent_incarnation),
    .persistent_queue_epoch(persistent_queue_epoch),
    .persistent_slot_id(persistent_slot_id),
    .persistent_command_id(persistent_command_id),
    .persistent_effect_id(persistent_effect_id),
    .persistent_next_attempt(persistent_next_attempt),
    .unresolved_valid(unresolved_valid),
    .unresolved_attempt(unresolved_attempt),
    .last_outcome(last_outcome),
    .last_resolved_attempt(last_resolved_attempt),
    .terminal_committed(terminal_committed),
    .terminal_conflict(terminal_conflict)
  );

  astra_capu_outcome_authority_shim_a6 #(
    .TAG_WIDTH(TAG_WIDTH),
    .ID_WIDTH(ID_WIDTH)
  ) authority_shim (
    .clk(clk),
    .logic_rst_n(logic_rst_n),
    .authority_load_valid(authority_load_valid),
    .authority_load_committed(authority_load_committed),
    .authority_load_tag(authority_load_tag),
    .authority_load_incarnation(authority_load_incarnation),
    .authority_load_queue_epoch(authority_load_queue_epoch),
    .authority_load_slot_id(authority_load_slot_id),
    .authority_load_command_id(authority_load_command_id),
    .authority_load_attempt_id(authority_load_attempt_id),
    .authority_load_effect_id(authority_load_effect_id),
    .authority_revoke_valid(authority_revoke_valid),
    .authority_revoke_tag(authority_revoke_tag),
    .authority_revoke_incarnation(authority_revoke_incarnation),
    .authority_revoke_queue_epoch(authority_revoke_queue_epoch),
    .authority_revoke_slot_id(authority_revoke_slot_id),
    .authority_revoke_command_id(authority_revoke_command_id),
    .authority_revoke_attempt_id(authority_revoke_attempt_id),
    .authority_revoke_effect_id(authority_revoke_effect_id),
    .command_valid(command_valid),
    .command_authority_tag(command_authority_tag),
    .command_incarnation(command_incarnation),
    .command_queue_epoch(command_queue_epoch),
    .command_slot_id(command_slot_id),
    .command_id(command_id),
    .command_attempt_id(command_attempt_id),
    .command_effect_id(command_effect_id),
    .persistent_valid(persistent_valid),
    .persistent_tag(persistent_tag),
    .persistent_incarnation(persistent_incarnation),
    .persistent_queue_epoch(persistent_queue_epoch),
    .persistent_slot_id(persistent_slot_id),
    .persistent_command_id(persistent_command_id),
    .persistent_effect_id(persistent_effect_id),
    .persistent_next_attempt(persistent_next_attempt),
    .unresolved_valid(unresolved_valid),
    .terminal_committed(terminal_committed),
    .terminal_conflict(terminal_conflict),
    .frontier_exhausted(frontier_exhausted),
    .reserve_accept(reserve_accept),
    .reserve_valid(reserve_valid),
    .reserve_tag(reserve_tag),
    .reserve_incarnation(reserve_incarnation),
    .reserve_queue_epoch(reserve_queue_epoch),
    .reserve_slot_id(reserve_slot_id),
    .reserve_command_id(reserve_command_id),
    .reserve_attempt_id(reserve_attempt_id),
    .reserve_effect_id(reserve_effect_id),
    .authority_load_accept(authority_load_accept),
    .authority_load_rejected(authority_load_rejected),
    .authority_revoke_accept(authority_revoke_accept),
    .authority_revoke_rejected(authority_revoke_rejected),
    .command_forward(command_forward),
    .command_rejected(command_rejected),
    .command_reject_code(command_reject_code),
    .active_valid(active_valid),
    .active_committed(active_committed),
    .attempt_spent(attempt_spent),
    .active_authority_tag(active_authority_tag),
    .active_incarnation(active_incarnation),
    .active_queue_epoch(active_queue_epoch),
    .active_slot_id(active_slot_id),
    .active_command_id(active_command_id),
    .active_attempt_id(active_attempt_id),
    .active_effect_id(active_effect_id)
  );

  astra_capu_effect_counter_a3 #(
    .COUNT_WIDTH(COUNT_WIDTH)
  ) effect_device (
    .clk(clk),
    .rst_n(cold_rst_n),
    .load_valid(device_state_load_valid),
    .load_effect_count(device_state_load_count),
    .command_valid(command_forward),
    .command_commit(command_commit),
    .command_accept(device_command_accept),
    .completion_valid(device_completion_valid),
    .effect_count(effect_count)
  );

endmodule
