module astra_capu_authenticated_reconciled_effect_device_a7 #(
  parameter integer DEVICE_WIDTH = 8,
  parameter integer TAG_WIDTH    = 8,
  parameter integer ID_WIDTH     = 4,
  parameter integer AUTH_WIDTH   = 16,
  parameter integer COUNT_WIDTH  = 16
)(
  input  logic                     clk,
  input  logic                     cold_rst_n,
  input  logic                     logic_rst_n,

  input  logic                     device_state_load_valid,
  input  logic [COUNT_WIDTH-1:0]   device_state_load_count,

  input  logic                     trust_provision_valid,
  input  logic [DEVICE_WIDTH-1:0]  trust_provision_device_id,
  input  logic [ID_WIDTH-1:0]      trust_provision_key_epoch,
  input  logic [AUTH_WIDTH-1:0]    trust_provision_secret,
  input  logic [ID_WIDTH-1:0]      trust_provision_next_receipt_seq,

  input  logic                     provision_valid,
  input  logic [TAG_WIDTH-1:0]     provision_tag,
  input  logic [ID_WIDTH-1:0]      provision_incarnation,
  input  logic [ID_WIDTH-1:0]      provision_queue_epoch,
  input  logic [ID_WIDTH-1:0]      provision_slot_id,
  input  logic [ID_WIDTH-1:0]      provision_command_id,
  input  logic [ID_WIDTH-1:0]      provision_effect_id,
  input  logic [ID_WIDTH-1:0]      provision_next_attempt,

  input  logic                     authority_load_valid,
  input  logic                     authority_load_committed,
  input  logic [TAG_WIDTH-1:0]     authority_load_tag,
  input  logic [ID_WIDTH-1:0]      authority_load_incarnation,
  input  logic [ID_WIDTH-1:0]      authority_load_queue_epoch,
  input  logic [ID_WIDTH-1:0]      authority_load_slot_id,
  input  logic [ID_WIDTH-1:0]      authority_load_command_id,
  input  logic [ID_WIDTH-1:0]      authority_load_attempt_id,
  input  logic [ID_WIDTH-1:0]      authority_load_effect_id,

  input  logic                     authority_revoke_valid,
  input  logic [TAG_WIDTH-1:0]     authority_revoke_tag,
  input  logic [ID_WIDTH-1:0]      authority_revoke_incarnation,
  input  logic [ID_WIDTH-1:0]      authority_revoke_queue_epoch,
  input  logic [ID_WIDTH-1:0]      authority_revoke_slot_id,
  input  logic [ID_WIDTH-1:0]      authority_revoke_command_id,
  input  logic [ID_WIDTH-1:0]      authority_revoke_attempt_id,
  input  logic [ID_WIDTH-1:0]      authority_revoke_effect_id,

  input  logic                     command_valid,
  input  logic                     command_commit,
  input  logic [TAG_WIDTH-1:0]     command_authority_tag,
  input  logic [ID_WIDTH-1:0]      command_incarnation,
  input  logic [ID_WIDTH-1:0]      command_queue_epoch,
  input  logic [ID_WIDTH-1:0]      command_slot_id,
  input  logic [ID_WIDTH-1:0]      command_id,
  input  logic [ID_WIDTH-1:0]      command_attempt_id,
  input  logic [ID_WIDTH-1:0]      command_effect_id,

  input  logic                     receipt_valid,
  input  logic [DEVICE_WIDTH-1:0]  receipt_device_id,
  input  logic [ID_WIDTH-1:0]      receipt_key_epoch,
  input  logic [ID_WIDTH-1:0]      receipt_seq,
  input  logic [TAG_WIDTH-1:0]     receipt_authority_tag,
  input  logic [ID_WIDTH-1:0]      receipt_incarnation,
  input  logic [ID_WIDTH-1:0]      receipt_queue_epoch,
  input  logic [ID_WIDTH-1:0]      receipt_slot_id,
  input  logic [ID_WIDTH-1:0]      receipt_command_id,
  input  logic [ID_WIDTH-1:0]      receipt_attempt_id,
  input  logic [ID_WIDTH-1:0]      receipt_effect_id,
  input  logic [2:0]               receipt_outcome,
  input  logic [AUTH_WIDTH-1:0]    receipt_auth_tag,

  output logic                     trust_provision_accept,
  output logic                     trust_provision_rejected,
  output logic                     receipt_auth_accept,
  output logic                     receipt_auth_rejected,
  output logic [2:0]               receipt_auth_reject_code,
  output logic [AUTH_WIDTH-1:0]    receipt_expected_auth_tag,
  output logic                     receipt_reconcile_accept,
  output logic                     receipt_reconcile_rejected,
  output logic [2:0]               receipt_reconcile_reject_code,

  output logic                     provision_accept,
  output logic                     provision_rejected,
  output logic                     reserve_valid,
  output logic                     reserve_accept,
  output logic                     reserve_rejected,
  output logic                     frontier_exhausted,
  output logic                     authority_load_accept,
  output logic                     authority_load_rejected,
  output logic                     authority_revoke_accept,
  output logic                     authority_revoke_rejected,
  output logic                     command_forward,
  output logic                     command_rejected,
  output logic [3:0]               command_reject_code,
  output logic                     device_command_accept,
  output logic                     device_completion_valid,
  output logic [COUNT_WIDTH-1:0]   effect_count,

  output logic                     trusted_valid,
  output logic [DEVICE_WIDTH-1:0]  trusted_device_id,
  output logic [ID_WIDTH-1:0]      trusted_key_epoch,
  output logic [AUTH_WIDTH-1:0]    trusted_secret,
  output logic [ID_WIDTH-1:0]      trusted_next_receipt_seq,
  output logic                     receipt_sequence_exhausted,

  output logic                     persistent_valid,
  output logic [TAG_WIDTH-1:0]     persistent_tag,
  output logic [ID_WIDTH-1:0]      persistent_incarnation,
  output logic [ID_WIDTH-1:0]      persistent_queue_epoch,
  output logic [ID_WIDTH-1:0]      persistent_slot_id,
  output logic [ID_WIDTH-1:0]      persistent_command_id,
  output logic [ID_WIDTH-1:0]      persistent_effect_id,
  output logic [ID_WIDTH-1:0]      persistent_next_attempt,
  output logic                     unresolved_valid,
  output logic [ID_WIDTH-1:0]      unresolved_attempt,
  output logic [2:0]               last_outcome,
  output logic [ID_WIDTH-1:0]      last_resolved_attempt,
  output logic                     terminal_committed,
  output logic                     terminal_conflict,

  output logic                     active_valid,
  output logic                     active_committed,
  output logic                     attempt_spent,
  output logic [TAG_WIDTH-1:0]     active_authority_tag,
  output logic [ID_WIDTH-1:0]      active_incarnation,
  output logic [ID_WIDTH-1:0]      active_queue_epoch,
  output logic [ID_WIDTH-1:0]      active_slot_id,
  output logic [ID_WIDTH-1:0]      active_command_id,
  output logic [ID_WIDTH-1:0]      active_attempt_id,
  output logic [ID_WIDTH-1:0]      active_effect_id
);

  logic verified_reconcile_valid;
  logic [TAG_WIDTH-1:0] verified_reconcile_tag;
  logic [ID_WIDTH-1:0] verified_reconcile_incarnation;
  logic [ID_WIDTH-1:0] verified_reconcile_queue_epoch;
  logic [ID_WIDTH-1:0] verified_reconcile_slot_id;
  logic [ID_WIDTH-1:0] verified_reconcile_command_id;
  logic [ID_WIDTH-1:0] verified_reconcile_attempt_id;
  logic [ID_WIDTH-1:0] verified_reconcile_effect_id;
  logic [2:0] verified_reconcile_outcome;

  astra_capu_authenticated_receipt_gate_a7 #(
    .DEVICE_WIDTH(DEVICE_WIDTH),
    .TAG_WIDTH(TAG_WIDTH),
    .ID_WIDTH(ID_WIDTH),
    .AUTH_WIDTH(AUTH_WIDTH)
  ) receipt_gate (
    .clk(clk),
    .cold_rst_n(cold_rst_n),
    .trust_provision_valid(trust_provision_valid),
    .trust_provision_device_id(trust_provision_device_id),
    .trust_provision_key_epoch(trust_provision_key_epoch),
    .trust_provision_secret(trust_provision_secret),
    .trust_provision_next_receipt_seq(trust_provision_next_receipt_seq),
    .receipt_valid(receipt_valid),
    .receipt_device_id(receipt_device_id),
    .receipt_key_epoch(receipt_key_epoch),
    .receipt_seq(receipt_seq),
    .receipt_authority_tag(receipt_authority_tag),
    .receipt_incarnation(receipt_incarnation),
    .receipt_queue_epoch(receipt_queue_epoch),
    .receipt_slot_id(receipt_slot_id),
    .receipt_command_id(receipt_command_id),
    .receipt_attempt_id(receipt_attempt_id),
    .receipt_effect_id(receipt_effect_id),
    .receipt_outcome(receipt_outcome),
    .receipt_auth_tag(receipt_auth_tag),
    .trust_provision_accept(trust_provision_accept),
    .trust_provision_rejected(trust_provision_rejected),
    .receipt_auth_accept(receipt_auth_accept),
    .receipt_auth_rejected(receipt_auth_rejected),
    .receipt_auth_reject_code(receipt_auth_reject_code),
    .receipt_expected_auth_tag(receipt_expected_auth_tag),
    .verified_reconcile_valid(verified_reconcile_valid),
    .verified_reconcile_tag(verified_reconcile_tag),
    .verified_reconcile_incarnation(verified_reconcile_incarnation),
    .verified_reconcile_queue_epoch(verified_reconcile_queue_epoch),
    .verified_reconcile_slot_id(verified_reconcile_slot_id),
    .verified_reconcile_command_id(verified_reconcile_command_id),
    .verified_reconcile_attempt_id(verified_reconcile_attempt_id),
    .verified_reconcile_effect_id(verified_reconcile_effect_id),
    .verified_reconcile_outcome(verified_reconcile_outcome),
    .trusted_valid(trusted_valid),
    .trusted_device_id(trusted_device_id),
    .trusted_key_epoch(trusted_key_epoch),
    .trusted_secret(trusted_secret),
    .trusted_next_receipt_seq(trusted_next_receipt_seq),
    .receipt_sequence_exhausted(receipt_sequence_exhausted)
  );

  astra_capu_reconciled_effect_device_a6 #(
    .TAG_WIDTH(TAG_WIDTH),
    .ID_WIDTH(ID_WIDTH),
    .COUNT_WIDTH(COUNT_WIDTH)
  ) a6_device (
    .clk(clk),
    .cold_rst_n(cold_rst_n),
    .logic_rst_n(logic_rst_n),
    .device_state_load_valid(device_state_load_valid),
    .device_state_load_count(device_state_load_count),
    .provision_valid(provision_valid),
    .provision_tag(provision_tag),
    .provision_incarnation(provision_incarnation),
    .provision_queue_epoch(provision_queue_epoch),
    .provision_slot_id(provision_slot_id),
    .provision_command_id(provision_command_id),
    .provision_effect_id(provision_effect_id),
    .provision_next_attempt(provision_next_attempt),
    .authority_load_valid(authority_load_valid),
    .authority_load_committed(authority_load_committed),
    .authority_load_tag(authority_load_tag),
    .authority_load_incarnation(authority_load_incarnation),
    .authority_load_queue_epoch(authority_load_queue_epoch),
    .authority_load_slot_id(authority_load_slot_id),
    .authority_load_command_id(authority_load_command_id),
    .authority_load_attempt_id(authority_load_attempt_id),
    .authority_load_effect_id(authority_load_effect_id),
    .authority_revoke_valid(authority_revoke_valid),
    .authority_revoke_tag(authority_revoke_tag),
    .authority_revoke_incarnation(authority_revoke_incarnation),
    .authority_revoke_queue_epoch(authority_revoke_queue_epoch),
    .authority_revoke_slot_id(authority_revoke_slot_id),
    .authority_revoke_command_id(authority_revoke_command_id),
    .authority_revoke_attempt_id(authority_revoke_attempt_id),
    .authority_revoke_effect_id(authority_revoke_effect_id),
    .command_valid(command_valid),
    .command_commit(command_commit),
    .command_authority_tag(command_authority_tag),
    .command_incarnation(command_incarnation),
    .command_queue_epoch(command_queue_epoch),
    .command_slot_id(command_slot_id),
    .command_id(command_id),
    .command_attempt_id(command_attempt_id),
    .command_effect_id(command_effect_id),
    .reconcile_valid(verified_reconcile_valid),
    .reconcile_tag(verified_reconcile_tag),
    .reconcile_incarnation(verified_reconcile_incarnation),
    .reconcile_queue_epoch(verified_reconcile_queue_epoch),
    .reconcile_slot_id(verified_reconcile_slot_id),
    .reconcile_command_id(verified_reconcile_command_id),
    .reconcile_attempt_id(verified_reconcile_attempt_id),
    .reconcile_effect_id(verified_reconcile_effect_id),
    .reconcile_outcome(verified_reconcile_outcome),
    .provision_accept(provision_accept),
    .provision_rejected(provision_rejected),
    .reserve_valid(reserve_valid),
    .reserve_accept(reserve_accept),
    .reserve_rejected(reserve_rejected),
    .reconcile_accept(receipt_reconcile_accept),
    .reconcile_rejected(receipt_reconcile_rejected),
    .reconcile_reject_code(receipt_reconcile_reject_code),
    .frontier_exhausted(frontier_exhausted),
    .authority_load_accept(authority_load_accept),
    .authority_load_rejected(authority_load_rejected),
    .authority_revoke_accept(authority_revoke_accept),
    .authority_revoke_rejected(authority_revoke_rejected),
    .command_forward(command_forward),
    .command_rejected(command_rejected),
    .command_reject_code(command_reject_code),
    .device_command_accept(device_command_accept),
    .device_completion_valid(device_completion_valid),
    .effect_count(effect_count),
    .persistent_valid(persistent_valid),
    .persistent_tag(persistent_tag),
    .persistent_incarnation(persistent_incarnation),
    .persistent_queue_epoch(persistent_queue_epoch),
    .persistent_slot_id(persistent_slot_id),
    .persistent_command_id(persistent_command_id),
    .persistent_effect_id(persistent_effect_id),
    .persistent_next_attempt(persistent_next_attempt),
    .unresolved_valid(unresolved_valid),
    .unresolved_attempt(unresolved_attempt),
    .last_outcome(last_outcome),
    .last_resolved_attempt(last_resolved_attempt),
    .terminal_committed(terminal_committed),
    .terminal_conflict(terminal_conflict),
    .active_valid(active_valid),
    .active_committed(active_committed),
    .attempt_spent(attempt_spent),
    .active_authority_tag(active_authority_tag),
    .active_incarnation(active_incarnation),
    .active_queue_epoch(active_queue_epoch),
    .active_slot_id(active_slot_id),
    .active_command_id(active_command_id),
    .active_attempt_id(active_attempt_id),
    .active_effect_id(active_effect_id)
  );

endmodule
